version: "3"
services:

  backend-db:
    container_name: backend-db
    image: mongo
    volumes:
      - backend-db-mongo:/backend-db-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rnapdbee
      - MONGO_INITDB_ROOT_PASSWORD=a1s2d3f4
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    depends_on:
      - backend-db
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring_data_mongodb_authentication-database=admin
      - spring_data_mongodb_username=rnapdbee
      - spring_data_mongodb_password=a1s2d3f4
      - spring_data_mongodb_database=backend-db
      - spring_data_mongodb_port=27017
      - spring_data_mongodb_host=localhost

volumes:
  backend-db-mongo: {}
