version: "3"

services:

  mongoDB:
    container_name: rnapdbee-mongoDB-container
    image: mongo:4.4.6
    environment:
      # Username and password can not be changed after volume creation, saved in volume!
      - MONGO_INITDB_ROOT_USERNAME=rnapdbee
      - MONGO_INITDB_ROOT_PASSWORD=a1s2d3f4
    ports:
      - "27017:27017"
    volumes:
      - rnapdbee-mongoDB-volume:/data/db
    networks:
      - rnapdbee-network

  backend:
    container_name: rnapdbee-backend-container
    depends_on:
      - mongoDB
    build: .
    image: rnapdbee-backend-image
    environment:
      - spring_data_mongodb_authentication-database=admin
      - spring_data_mongodb_username=rnapdbee
      - spring_data_mongodb_password=a1s2d3f4
      - spring_data_mongodb_database=backend-db
      - spring_data_mongodb_port=27017
      - spring_data_mongodb_host=rnapdbee-mongoDB-container
      - rnapdbee_engine_global_host=http://rnapdbee-engine-container:8081/calculation-api/
      - document_storage_days=14
    ports:
      - "8080:8080"
    volumes:
      - rnapdbee-backend-volume:/resources/tmp
    networks:
      - rnapdbee-network

volumes:
  rnapdbee-mongoDB-volume:
  rnapdbee-backend-volume:

networks:
  rnapdbee-network: